import type { AutohallSymfonyIncludeKey } from './export-contracts.types';
import { SYMFONY_REQUIRED_RUNTIME_CONTEXT } from './export-contracts.registry';
import { resolveSymfonyIncludePath } from './symfony-include-mapping';

export function renderSymfonyTestDriveTwigSlot(input: {
  includeKey: AutohallSymfonyIncludeKey;
}): string {
  const includePath = resolveSymfonyIncludePath(input.includeKey);
  const runtimeList = SYMFONY_REQUIRED_RUNTIME_CONTEXT.join(', ');

  return `{# Auto Hall — Campaign Lead Hero Symfony form slot #}
{# Generated by AutoHall LP Builder. Do not paste arbitrary Twig from the Studio. #}
{# Include key: ${input.includeKey} #}
{# Required controller/runtime variables: ${runtimeList} #}
{# The controller must build formtestdrive via Symfony Form (TestdriveType) and Doctrine models. #}

<div
  class="lp-campaign-lead-hero lp-campaign-lead-hero__symfony-form-slot"
  data-form-provider="autohall_symfony_testdrive"
  data-include-key="${input.includeKey}"
>
  {% include '${includePath}' with {
    formtestdrive: formtestdrive,
    currentLocale: currentLocale
  } only %}
</div>
`;
}

export function renderSymfonyCampaignPageExample(input: {
  pageTitle: string;
  fragmentTemplatePath: string;
}): string {
  const safeTitle = input.pageTitle.replace(/'/g, "\\'");

  return `{# Auto Hall — Example Symfony page for a builder campaign #}
{# Copy to your Symfony templates tree and wire a controller action. #}
{# Fragment path below assumes you placed campaign-lead-hero.fragment.html.twig alongside this file. #}

{% extends 'base.html.twig' %}

{% block title %}{{ page_title|default('${safeTitle}') }}{% endblock %}

{% block body %}
  <main class="autohall-campaign-page" data-export-source="autohall-lp-builder">
    {% include '${input.fragmentTemplatePath}' %}
  </main>
{% endblock %}
`;
}
