server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA — React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_vary on;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        image/svg+xml;
}
