import type { InspectorControl } from '../block-registry/inspector-control.types';
import {
  campaignLeadHeroBlockVisualDefaults,
  ctaBandBlockVisualDefaults,
  faqBlockVisualDefaults,
  heroVehicleOfferBlockVisualDefaults,
  trustBarBlockVisualDefaults,
} from './block-visual.registry';

const SEGMENTED = 'segmented' as const;

export const campaignLeadHeroBlockVisualControls: InspectorControl[] = [
  {
    key: 'clh-bv-hero-height',
    propKey: 'heroHeight',
    type: SEGMENTED,
    label: 'Hauteur hero',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.heroHeight,
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'default', label: 'Standard' },
      { value: 'tall', label: 'Haut' },
      { value: 'viewport', label: 'Plein écran' },
    ],
  },
  {
    key: 'clh-bv-vertical-align',
    propKey: 'verticalAlignment',
    type: SEGMENTED,
    label: 'Alignement vertical',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.verticalAlignment,
    options: [
      { value: 'top', label: 'Haut' },
      { value: 'center', label: 'Centre' },
      { value: 'bottom', label: 'Bas' },
    ],
  },
  {
    key: 'clh-bv-content-max-width',
    propKey: 'contentMaxWidth',
    type: SEGMENTED,
    label: 'Largeur contenu',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.contentMaxWidth,
    options: [
      { value: 'sm', label: 'S' },
      { value: 'md', label: 'M' },
      { value: 'lg', label: 'L' },
    ],
  },
  {
    key: 'clh-bv-media-ratio',
    propKey: 'mediaRatio',
    type: SEGMENTED,
    label: 'Ratio média',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.mediaRatio,
    options: [
      { value: 'portrait', label: 'Portrait' },
      { value: 'square', label: 'Carré' },
      { value: 'landscape', label: 'Paysage' },
      { value: 'cinematic', label: 'Ciné' },
      { value: 'full', label: 'Plein' },
    ],
  },
  {
    key: 'clh-bv-media-emphasis',
    propKey: 'mediaEmphasis',
    type: SEGMENTED,
    label: 'Emphase visuelle',
    tab: 'design',
    group: 'Emphase',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.mediaEmphasis,
    options: [
      { value: 'balanced', label: 'Équilibré' },
      { value: 'media_focus', label: 'Média' },
      { value: 'form_focus', label: 'Formulaire' },
    ],
  },
  {
    key: 'clh-bv-form-width',
    propKey: 'formWidth',
    type: SEGMENTED,
    label: 'Largeur formulaire',
    tab: 'design',
    group: 'Formulaire',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.formWidth,
    options: [
      { value: 'sm', label: 'S' },
      { value: 'md', label: 'M' },
      { value: 'lg', label: 'L' },
    ],
  },
  {
    key: 'clh-bv-form-position',
    propKey: 'formPosition',
    type: SEGMENTED,
    label: 'Position formulaire',
    tab: 'design',
    group: 'Formulaire',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.formPosition,
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'right', label: 'Droite' },
    ],
  },
  {
    key: 'clh-bv-form-card',
    propKey: 'formCardStyle',
    type: SEGMENTED,
    label: 'Style carte formulaire',
    tab: 'design',
    group: 'Formulaire',
    store: 'blockVisual',
    defaultValue: campaignLeadHeroBlockVisualDefaults.formCardStyle,
    options: [
      { value: 'flat', label: 'Plat' },
      { value: 'elevated', label: 'Élevé' },
      { value: 'glass', label: 'Glass' },
      { value: 'bordered', label: 'Bordure' },
    ],
  },
];

export const heroVehicleOfferBlockVisualControls: InspectorControl[] = [
  {
    key: 'hvo-bv-hero-height',
    propKey: 'heroHeight',
    type: SEGMENTED,
    label: 'Hauteur hero',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.heroHeight,
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'default', label: 'Standard' },
      { value: 'tall', label: 'Haut' },
    ],
  },
  {
    key: 'hvo-bv-layout-emphasis',
    propKey: 'layoutEmphasis',
    type: SEGMENTED,
    label: 'Emphase mise en page',
    tab: 'design',
    group: 'Emphase',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.layoutEmphasis,
    options: [
      { value: 'balanced', label: 'Équilibré' },
      { value: 'vehicle_focus', label: 'Véhicule' },
      { value: 'offer_focus', label: 'Offre' },
    ],
  },
  {
    key: 'hvo-bv-image-scale',
    propKey: 'vehicleImageScale',
    type: SEGMENTED,
    label: 'Échelle visuel véhicule',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.vehicleImageScale,
    options: [
      { value: 'sm', label: 'S' },
      { value: 'md', label: 'M' },
      { value: 'lg', label: 'L' },
      { value: 'xl', label: 'XL' },
    ],
  },
  {
    key: 'hvo-bv-image-position',
    propKey: 'vehicleImagePosition',
    type: SEGMENTED,
    label: 'Position visuel',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.vehicleImagePosition,
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'center', label: 'Centre' },
      { value: 'right', label: 'Droite' },
    ],
  },
  {
    key: 'hvo-bv-offer-card',
    propKey: 'offerCardStyle',
    type: SEGMENTED,
    label: 'Style carte offre',
    tab: 'design',
    group: 'Carte offre',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.offerCardStyle,
    options: [
      { value: 'flat', label: 'Plat' },
      { value: 'elevated', label: 'Élevé' },
      { value: 'bordered', label: 'Bordure' },
      { value: 'glass', label: 'Glass' },
    ],
  },
  {
    key: 'hvo-bv-price-emphasis',
    propKey: 'priceEmphasis',
    type: SEGMENTED,
    label: 'Emphase prix',
    tab: 'design',
    group: 'Emphase',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.priceEmphasis,
    options: [
      { value: 'subtle', label: 'Discret' },
      { value: 'standard', label: 'Standard' },
      { value: 'strong', label: 'Fort' },
    ],
  },
  {
    key: 'hvo-bv-badge-placement',
    propKey: 'badgePlacement',
    type: SEGMENTED,
    label: 'Placement badge',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: heroVehicleOfferBlockVisualDefaults.badgePlacement,
    options: [
      { value: 'top', label: 'Haut' },
      { value: 'media', label: 'Média' },
      { value: 'content', label: 'Contenu' },
    ],
  },
];

export const faqBlockVisualControls: InspectorControl[] = [
  {
    key: 'faq-bv-style',
    propKey: 'faqStyle',
    type: SEGMENTED,
    label: 'Style FAQ',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: faqBlockVisualDefaults.faqStyle,
    options: [
      { value: 'clean', label: 'Épuré' },
      { value: 'boxed', label: 'Encadré' },
      { value: 'divided', label: 'Séparé' },
    ],
  },
  {
    key: 'faq-bv-density',
    propKey: 'faqDensity',
    type: SEGMENTED,
    label: 'Densité',
    tab: 'design',
    group: 'Densité',
    store: 'blockVisual',
    defaultValue: faqBlockVisualDefaults.faqDensity,
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'comfortable', label: 'Confort' },
      { value: 'spacious', label: 'Aéré' },
    ],
  },
  {
    key: 'faq-bv-icon',
    propKey: 'iconStyle',
    type: SEGMENTED,
    label: 'Icône accordéon',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: faqBlockVisualDefaults.iconStyle,
    options: [
      { value: 'plus', label: 'Plus' },
      { value: 'chevron', label: 'Chevron' },
      { value: 'none', label: 'Aucune' },
    ],
  },
];

export const ctaBandBlockVisualControls: InspectorControl[] = [
  {
    key: 'cta-bv-layout',
    propKey: 'ctaLayout',
    type: SEGMENTED,
    label: 'Disposition CTA',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: ctaBandBlockVisualDefaults.ctaLayout,
    options: [
      { value: 'inline', label: 'Inline' },
      { value: 'stacked', label: 'Empilé' },
      { value: 'split', label: 'Split' },
    ],
  },
  {
    key: 'cta-bv-intensity',
    propKey: 'ctaIntensity',
    type: SEGMENTED,
    label: 'Intensité visuelle',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: ctaBandBlockVisualDefaults.ctaIntensity,
    options: [
      { value: 'subtle', label: 'Discret' },
      { value: 'brand', label: 'Marque' },
      { value: 'dark', label: 'Sombre' },
    ],
  },
  {
    key: 'cta-bv-alignment',
    propKey: 'ctaAlignment',
    type: SEGMENTED,
    label: 'Alignement',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: ctaBandBlockVisualDefaults.ctaAlignment,
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'center', label: 'Centre' },
    ],
  },
];

export const trustBarBlockVisualControls: InspectorControl[] = [
  {
    key: 'trust-bv-layout',
    propKey: 'trustLayout',
    type: SEGMENTED,
    label: 'Disposition',
    tab: 'design',
    group: 'Mise en page du bloc',
    store: 'blockVisual',
    defaultValue: trustBarBlockVisualDefaults.trustLayout,
    options: [
      { value: 'row', label: 'Ligne' },
      { value: 'grid', label: 'Grille' },
    ],
  },
  {
    key: 'trust-bv-density',
    propKey: 'trustDensity',
    type: SEGMENTED,
    label: 'Densité',
    tab: 'design',
    group: 'Densité',
    store: 'blockVisual',
    defaultValue: trustBarBlockVisualDefaults.trustDensity,
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'comfortable', label: 'Confort' },
    ],
  },
  {
    key: 'trust-bv-style',
    propKey: 'trustStyle',
    type: SEGMENTED,
    label: 'Style',
    tab: 'design',
    group: 'Visuel',
    store: 'blockVisual',
    defaultValue: trustBarBlockVisualDefaults.trustStyle,
    options: [
      { value: 'minimal', label: 'Minimal' },
      { value: 'cards', label: 'Cartes' },
      { value: 'premium', label: 'Premium' },
    ],
  },
];

const BLOCK_VISUAL_CONTROLS: Record<string, InspectorControl[]> = {
  campaign_lead_hero: campaignLeadHeroBlockVisualControls,
  hero_vehicle_offer: heroVehicleOfferBlockVisualControls,
  faq: faqBlockVisualControls,
  cta_band: ctaBandBlockVisualControls,
  trust_bar: trustBarBlockVisualControls,
};

export function getBlockVisualInspectorControls(blockType: string): InspectorControl[] {
  return BLOCK_VISUAL_CONTROLS[blockType] ?? [];
}
