/** Villes principales du réseau Auto Hall (alignées campagnes offresav / fordpromo). */
export const AUTOHALL_CITIES = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Tanger',
  'Agadir',
  'Dakhla',
  'El Jadida',
  'Errachidia',
  'Fès',
  'Kénitra',
  'Karia',
  'Meknès',
  'Oujda',
  'Nador',
  'Rommani',
  'Safi',
  'Settat',
  'Salé',
  'Tétouan',
  'Béni Mellal',
  'Berkane',
  'Al Hoceima',
  'Tiznit',
  'Taroudant',
  'Khouribga',
  'Tifelt',
  'Mohammedia',
  'Ait Melloul',
] as const;
