import type { InspectorControl } from '../../block-registry/inspector-control.types';
import { HERO_CROP_PRESETS } from '../hero-vehicle-offer/hero-image-controls';
import { CAMPAIGN_LEAD_HERO_TYPE } from './campaign-lead-hero.types';

const CROP_OPTIONS = HERO_CROP_PRESETS.map((value) => ({
  value,
  label:
    value === 'center'
      ? 'Centre'
      : value === 'top'
        ? 'Haut'
        : value === 'bottom'
          ? 'Bas'
          : value === 'left'
            ? 'Gauche'
            : value === 'right'
              ? 'Droite'
              : 'Personnalisé',
}));

const DUAL_LAYOUTS = ['dual_media_form_right', 'dual_media_form_left'];

export const campaignLeadHeroInspectorControls: InspectorControl[] = [
  {
    key: 'clh-brand',
    propKey: 'brandId',
    type: 'brand',
    label: 'Marque',
    tab: 'content',
    group: 'Campagne',
    defaultValue: 'chery',
  },
  {
    key: 'clh-campaign-title',
    propKey: 'campaignTitle',
    type: 'text',
    label: 'Titre campagne',
    tab: 'content',
    group: 'Campagne',
  },
  {
    key: 'clh-campaign-subtitle',
    propKey: 'campaignSubtitle',
    type: 'textarea',
    label: 'Sous-titre campagne',
    tab: 'content',
    group: 'Campagne',
  },
  {
    key: 'clh-offer-badge',
    propKey: 'offerBadge',
    type: 'text',
    label: 'Badge offre',
    tab: 'content',
    group: 'Campagne',
  },
  {
    key: 'clh-form-title',
    propKey: 'formTitle',
    type: 'text',
    label: 'Titre formulaire',
    tab: 'content',
    group: 'Formulaire',
  },
  {
    key: 'clh-form-subtitle',
    propKey: 'formSubtitle',
    type: 'textarea',
    label: 'Sous-titre formulaire',
    tab: 'content',
    group: 'Formulaire',
  },
  {
    key: 'clh-step-label',
    propKey: 'formStepLabel',
    type: 'text',
    label: 'Libellé étape',
    tab: 'content',
    group: 'Formulaire',
  },
  {
    key: 'clh-field-label',
    propKey: 'formPrimaryFieldLabel',
    type: 'text',
    label: 'Champ principal',
    tab: 'content',
    group: 'Formulaire',
  },
  {
    key: 'clh-cta',
    propKey: 'formCtaLabel',
    type: 'text',
    label: 'CTA formulaire',
    tab: 'content',
    group: 'Formulaire',
  },
  {
    key: 'clh-form-theme',
    propKey: 'formTheme',
    type: 'select',
    label: 'Thème formulaire',
    tab: 'design',
    store: 'design',
    group: 'Style formulaire',
    defaultValue: 'light',
    options: [
      { value: 'light', label: 'Clair (Auto Hall)' },
      { value: 'dark', label: 'Sombre' },
      { value: 'glass', label: 'Verre dépoli' },
    ],
  },
  {
    key: 'clh-tone',
    propKey: 'tone',
    type: 'select',
    label: 'Ambiance',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: 'light',
    options: [
      { value: 'light', label: 'Clair' },
      { value: 'dark', label: 'Sombre' },
      { value: 'brand', label: 'Marque' },
    ],
  },
  {
    key: 'clh-show-badge',
    propKey: 'showOfferBadge',
    type: 'boolean',
    label: 'Afficher le badge offre',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: true,
  },
  {
    key: 'clh-progress',
    propKey: 'showProgressBar',
    type: 'boolean',
    label: 'Barre de progression',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: true,
  },
  {
    key: 'clh-layout',
    propKey: 'layoutVariant',
    type: 'layout-variant',
    label: 'Disposition',
    tab: 'layout',
    group: 'Structure',
    defaultValue: 'media_left_form_right',
    options: [
      { value: 'media_left_form_right', label: 'Image gauche · formulaire droite' },
      { value: 'form_left_media_right', label: 'Formulaire gauche · image droite' },
      { value: 'background_media_form_right', label: 'Fond image · formulaire droite' },
      { value: 'background_media_form_left', label: 'Fond image · formulaire gauche' },
      { value: 'dual_media_form_right', label: 'Double visuel · formulaire droite' },
      { value: 'dual_media_form_left', label: 'Double visuel · formulaire gauche' },
    ],
  },
  {
    key: 'clh-content-placement',
    propKey: 'contentPlacement',
    type: 'select',
    label: 'Placement du texte campagne',
    tab: 'layout',
    group: 'Structure',
    defaultValue: 'hidden',
    options: [
      { value: 'hidden', label: 'Masqué (visuel seul)' },
      { value: 'overlay_media', label: 'Superposé sur le visuel' },
      { value: 'beside_form', label: 'À côté du formulaire' },
    ],
  },
  {
    key: 'clh-primary-image',
    propKey: 'primaryImage',
    type: 'image',
    label: 'Image principale (desktop)',
    description: 'Visuel campagne — importez ou choisissez dans la bibliothèque.',
    tab: 'media',
    group: 'Visuels',
    assetKey: 'primaryImage',
    urlKey: 'primaryImageUrl',
    altKey: 'primaryImageAlt',
  },
  {
    key: 'clh-primary-alt',
    propKey: 'primaryImageAlt',
    type: 'text',
    label: 'Texte alternatif (alt)',
    tab: 'media',
    group: 'Visuels',
    placeholder: 'Ex. Véhicule en concession',
    maxLength: 120,
  },
  {
    key: 'clh-secondary-image',
    propKey: 'secondaryImage',
    type: 'image',
    label: 'Image secondaire',
    tab: 'media',
    group: 'Visuels',
    assetKey: 'secondaryImage',
    urlKey: 'secondaryImageUrl',
    altKey: 'secondaryImageAlt',
    visibleWhen: { prop: 'layoutVariant', oneOf: DUAL_LAYOUTS },
  },
  {
    key: 'clh-secondary-alt',
    propKey: 'secondaryImageAlt',
    type: 'text',
    label: 'Texte alternatif secondaire',
    tab: 'media',
    group: 'Visuels',
    visibleWhen: { prop: 'layoutVariant', oneOf: DUAL_LAYOUTS },
  },
  {
    key: 'clh-mobile-image',
    propKey: 'mobileImage',
    type: 'image',
    label: 'Image mobile (optionnel)',
    description: 'Affichée sur petits écrans. Les réglages de recadrage ci-dessous s’appliquent aussi.',
    tab: 'media',
    group: 'Responsive',
    assetKey: 'mobileImage',
    urlKey: 'mobileImageUrl',
  },
  {
    key: 'clh-image-fit',
    propKey: 'imageFit',
    type: 'select',
    label: 'Ajustement image',
    tab: 'media',
    group: 'Recadrage',
    defaultValue: 'cover',
    options: [
      { value: 'cover', label: 'Remplir (cover)' },
      { value: 'contain', label: 'Contenir (contain)' },
    ],
  },
  {
    key: 'clh-image-position',
    propKey: 'imagePosition',
    type: 'select',
    label: 'Position image',
    tab: 'media',
    group: 'Recadrage',
    defaultValue: 'center',
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'center', label: 'Centre' },
      { value: 'right', label: 'Droite' },
    ],
  },
  {
    key: 'clh-crop',
    propKey: 'cropPreset',
    type: 'select',
    label: 'Recadrage',
    tab: 'media',
    group: 'Recadrage',
    defaultValue: 'center',
    options: CROP_OPTIONS,
  },
  {
    key: 'clh-focal-x',
    propKey: 'focalPointX',
    type: 'number',
    label: 'Point focal horizontal (%)',
    description: 'Utilisé quand recadrage personnalisé est actif.',
    tab: 'media',
    group: 'Recadrage',
    min: 0,
    max: 100,
    defaultValue: 50,
    visibleWhen: { prop: 'cropPreset', equals: 'custom' },
  },
  {
    key: 'clh-focal-y',
    propKey: 'focalPointY',
    type: 'number',
    label: 'Point focal vertical (%)',
    description: 'Utilisé quand recadrage personnalisé est actif.',
    tab: 'media',
    group: 'Recadrage',
    min: 0,
    max: 100,
    defaultValue: 50,
    visibleWhen: { prop: 'cropPreset', equals: 'custom' },
  },
  {
    key: 'clh-overlay',
    propKey: 'overlayIntensity',
    type: 'select',
    label: 'Overlay',
    tab: 'media',
    group: 'Recadrage',
    defaultValue: 'light',
    options: [
      { value: 'none', label: 'Aucun' },
      { value: 'light', label: 'Léger' },
      { value: 'medium', label: 'Moyen' },
      { value: 'heavy', label: 'Fort' },
    ],
  },
  {
    key: 'clh-legal',
    propKey: 'legalText',
    type: 'textarea',
    label: 'Texte légal',
    tab: 'advanced',
    group: 'Conformité',
  },
  {
    key: 'clh-footer',
    propKey: 'footerText',
    type: 'textarea',
    label: 'Pied de formulaire',
    tab: 'advanced',
    group: 'Conformité',
    description:
      'Aperçu formulaire statique — l’intégration provider lead arrive au prochain commit.',
  },
];

export const CAMPAIGN_LEAD_HERO_INSPECTOR_BLOCK_TYPE = CAMPAIGN_LEAD_HERO_TYPE;
