import { IMAGE_STYLE_DEFAULTS } from '../fields/field-definitions';
import type { BlockLibraryEntry } from './types';

export const BLOCK_LIBRARY: BlockLibraryEntry[] = [
  {
    id: 'heading',
    name: 'Titre',
    category: 'text',
    description: 'Titre H1, H2 ou H3 stylé.',
    icon: 'heading',
    componentType: 'HeadingBlock',
    defaultProps: { text: 'Nouveau titre', level: 'h2', fontSize: 'lg', fontWeight: 'bold' },
  },
  {
    id: 'paragraph',
    name: 'Paragraphe',
    category: 'text',
    description: 'Bloc de texte courant.',
    icon: 'text',
    componentType: 'ParagraphBlock',
    defaultProps: { text: 'Votre paragraphe ici.', fontSize: 'md' },
  },
  {
    id: 'button',
    name: 'Bouton',
    category: 'conversion',
    description: 'Bouton d\'action avec destination.',
    icon: 'mouse-pointer',
    componentType: 'ButtonBlock',
    defaultProps: { label: 'En savoir plus', href: '#lead-form', buttonStyle: 'primary' },
  },
  {
    id: 'badge',
    name: 'Badge',
    category: 'text',
    description: 'Étiquette promotionnelle.',
    icon: 'tag',
    componentType: 'BadgeBlock',
    defaultProps: { text: 'Nouveau', tone: 'brand' },
  },
  {
    id: 'image',
    name: 'Image',
    category: 'media',
    description: 'Visuel seul avec légende optionnelle.',
    icon: 'image',
    componentType: 'MediaImage',
    defaultProps: { imageAlt: 'Image Auto Hall', alignment: 'center', ...IMAGE_STYLE_DEFAULTS },
  },
  {
    id: 'text-image',
    name: 'Image + texte',
    category: 'media',
    description: 'Bloc éditorial combiné.',
    icon: 'layout',
    componentType: 'TextImageBlock',
    defaultProps: {
      title: 'Titre',
      text: '',
      layout: 'image_right',
      imageAlt: 'Visuel',
      ...IMAGE_STYLE_DEFAULTS,
    },
  },
  {
    id: 'card',
    name: 'Carte',
    category: 'layout',
    description: 'Carte de contenu isolée.',
    icon: 'square',
    componentType: 'CardBlock',
    defaultProps: { title: 'Carte', text: '', cardRadius: 'soft' },
  },
  {
    id: 'quote',
    name: 'Citation',
    category: 'text',
    description: 'Témoignage ou citation mise en avant.',
    icon: 'quote',
    componentType: 'QuoteBlock',
    defaultProps: { quote: 'Citation client', author: 'Client', alignment: 'center' },
  },
  {
    id: 'stats',
    name: 'Chiffres clés',
    category: 'marketing',
    description: 'Statistiques en bandeau.',
    icon: 'bar-chart',
    componentType: 'StatsBlock',
    defaultProps: {
      tone: 'brand',
      items: [{ value: '100+', label: 'Clients' }],
    },
  },
  {
    id: 'divider',
    name: 'Séparateur',
    category: 'layout',
    description: 'Ligne ou espace entre blocs.',
    icon: 'minus',
    componentType: 'DividerBlock',
    defaultProps: { style: 'line' },
  },
  {
    id: 'spacer',
    name: 'Espacement',
    category: 'layout',
    description: 'Espace vertical ajustable.',
    icon: 'move-vertical',
    componentType: 'Spacer',
    defaultProps: { size: 'md' },
  },
  {
    id: 'stack',
    name: 'Empilement',
    category: 'layout',
    description: 'Conteneur vertical pour composer des blocs.',
    icon: 'layers',
    componentType: 'StackBlock',
    defaultProps: { alignment: 'left', maxWidth: 'standard', gap: 'normal' },
  },
];

export function getBlockLibraryEntry(id: string): BlockLibraryEntry | undefined {
  return BLOCK_LIBRARY.find((b) => b.id === id);
}
