import type { InspectorControl } from '../../block-registry/inspector-control.types';
import { HERO_CROP_PRESETS } from './hero-image-controls';
import { HERO_VEHICLE_OFFER_TYPE } from './hero-vehicle-offer.types';

const CROP_OPTIONS = HERO_CROP_PRESETS.map((value) => ({
  value,
  label:
    value === 'center'
      ? 'Centre'
      : value === 'top'
        ? 'Haut'
        : value === 'bottom'
          ? 'Bas'
          : value === 'left'
            ? 'Gauche'
            : value === 'right'
              ? 'Droite'
              : 'Personnalisé',
}));

export const heroVehicleOfferInspectorControls: InspectorControl[] = [
  {
    key: 'hvo-brand',
    propKey: 'brandId',
    type: 'brand',
    label: 'Marque',
    description: 'Applique les couleurs et le ton de la marque sur le hero.',
    tab: 'content',
    group: 'Identité',
    defaultValue: 'ford',
  },
  {
    key: 'hvo-model',
    propKey: 'modelName',
    type: 'text',
    label: 'Modèle',
    tab: 'content',
    group: 'Identité',
    placeholder: 'Ex. Ford Ranger',
    maxLength: 80,
  },
  {
    key: 'hvo-headline',
    propKey: 'headline',
    type: 'text',
    label: 'Titre principal',
    tab: 'content',
    group: 'Message',
    maxLength: 120,
  },
  {
    key: 'hvo-subheadline',
    propKey: 'subheadline',
    type: 'textarea',
    label: 'Sous-titre',
    tab: 'content',
    group: 'Message',
    maxLength: 240,
  },
  {
    key: 'hvo-offer',
    propKey: 'offerLabel',
    type: 'text',
    label: 'Badge offre',
    tab: 'content',
    group: 'Offre',
    maxLength: 48,
  },
  {
    key: 'hvo-price',
    propKey: 'priceText',
    type: 'text',
    label: 'Prix / mention',
    tab: 'content',
    group: 'Offre',
    maxLength: 64,
  },
  {
    key: 'hvo-cta-primary',
    propKey: 'primaryCtaLabel',
    type: 'text',
    label: 'CTA principal',
    tab: 'content',
    group: 'Actions',
  },
  {
    key: 'hvo-cta-secondary',
    propKey: 'secondaryCtaLabel',
    type: 'text',
    label: 'CTA secondaire',
    tab: 'content',
    group: 'Actions',
  },
  {
    key: 'hvo-tone',
    propKey: 'tone',
    type: 'select',
    label: 'Ambiance',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: 'brand',
    options: [
      { value: 'light', label: 'Clair' },
      { value: 'dark', label: 'Sombre' },
      { value: 'brand', label: 'Marque' },
    ],
  },
  {
    key: 'hvo-density',
    propKey: 'density',
    type: 'select',
    label: 'Densité',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: 'comfortable',
    options: [
      { value: 'compact', label: 'Compact' },
      { value: 'comfortable', label: 'Confortable' },
      { value: 'immersive', label: 'Immersif' },
    ],
  },
  {
    key: 'hvo-cta-style',
    propKey: 'ctaStyle',
    type: 'select',
    label: 'Style CTA',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: 'primary',
    options: [
      { value: 'primary', label: 'Plein' },
      { value: 'outline', label: 'Contour' },
      { value: 'ghost', label: 'Discret' },
    ],
  },
  {
    key: 'hvo-show-badge',
    propKey: 'showOfferBadge',
    type: 'boolean',
    label: 'Afficher le badge offre',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: true,
  },
  {
    key: 'hvo-align',
    propKey: 'alignContent',
    type: 'segmented',
    label: 'Alignement contenu',
    tab: 'design',
    store: 'design',
    group: 'Style visuel',
    defaultValue: 'left',
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'center', label: 'Centre' },
    ],
  },
  {
    key: 'hvo-layout',
    propKey: 'layoutVariant',
    type: 'layout-variant',
    label: 'Disposition',
    tab: 'layout',
    group: 'Structure',
    defaultValue: 'split-media-right',
    options: [
      { value: 'split-media-right', label: 'Média à droite' },
      { value: 'split-media-left', label: 'Média à gauche' },
      { value: 'full-bleed-overlay', label: 'Plein écran' },
      { value: 'stacked-mobile', label: 'Empilé mobile' },
    ],
  },
  {
    key: 'hvo-hero-image',
    propKey: 'heroImage',
    type: 'image',
    label: 'Image hero (desktop)',
    description: 'Visuel principal — sélectionnez un asset de la page ou remplacez.',
    tab: 'media',
    group: 'Visuels',
    assetKey: 'heroImage',
    urlKey: 'heroImageUrl',
    altKey: 'heroImageAlt',
  },
  {
    key: 'hvo-mobile-image',
    propKey: 'mobileImage',
    type: 'image',
    label: 'Image mobile (optionnel)',
    tab: 'media',
    group: 'Visuels',
    assetKey: 'mobileImage',
    urlKey: 'mobileImageUrl',
  },
  {
    key: 'hvo-alt',
    propKey: 'heroImageAlt',
    type: 'text',
    label: 'Texte alternatif (alt)',
    description: 'Accessibilité et SEO — décrit le visuel du véhicule.',
    tab: 'media',
    group: 'Visuels',
    placeholder: 'Ex. Ford Ranger vue 3/4',
    maxLength: 120,
  },
  {
    key: 'hvo-fit',
    propKey: 'imageFit',
    type: 'select',
    label: 'Ajustement image',
    tab: 'media',
    group: 'Cadrage',
    defaultValue: 'cover',
    options: [
      { value: 'cover', label: 'Remplir (cover)' },
      { value: 'contain', label: 'Contenir (contain)' },
    ],
  },
  {
    key: 'hvo-position',
    propKey: 'imagePosition',
    type: 'select',
    label: 'Position image',
    tab: 'media',
    group: 'Cadrage',
    defaultValue: 'right',
    options: [
      { value: 'left', label: 'Gauche' },
      { value: 'right', label: 'Droite' },
      { value: 'background', label: 'Arrière-plan' },
    ],
  },
  {
    key: 'hvo-crop',
    propKey: 'cropPreset',
    type: 'select',
    label: 'Recadrage (point focal)',
    tab: 'media',
    group: 'Cadrage',
    defaultValue: 'center',
    options: CROP_OPTIONS,
  },
  {
    key: 'hvo-focal-x',
    propKey: 'focalPointX',
    type: 'number',
    label: 'Focal X (%)',
    tab: 'media',
    group: 'Cadrage',
    min: 0,
    max: 100,
    defaultValue: 50,
    visibleWhen: { prop: 'cropPreset', equals: 'custom' },
  },
  {
    key: 'hvo-focal-y',
    propKey: 'focalPointY',
    type: 'number',
    label: 'Focal Y (%)',
    tab: 'media',
    group: 'Cadrage',
    min: 0,
    max: 100,
    defaultValue: 50,
    visibleWhen: { prop: 'cropPreset', equals: 'custom' },
  },
  {
    key: 'hvo-overlay',
    propKey: 'overlayIntensity',
    type: 'select',
    label: 'Intensité overlay',
    tab: 'media',
    group: 'Cadrage',
    defaultValue: 'medium',
    options: [
      { value: 'none', label: 'Aucun' },
      { value: 'light', label: 'Léger' },
      { value: 'medium', label: 'Moyen' },
      { value: 'heavy', label: 'Fort' },
    ],
  },
];

export const HERO_VEHICLE_OFFER_INSPECTOR_BLOCK_TYPE = HERO_VEHICLE_OFFER_TYPE;
