import type { BrandPreset, BrandPresetId } from './brand-preset.types';

const EUROPEAN_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'vehicle_features',
  'pricing_trim',
  'lead_form',
  'final_cta',
  'footer_legal',
];

const AMERICAN_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'vehicle_range',
  'benefits',
  'cta_band',
  'lead_form',
  'footer_legal',
];

const JAPANESE_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'trust_bar',
  'vehicle_features',
  'benefits',
  'lead_form',
  'footer_legal',
];

const CHINESE_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'pricing_trim',
  'benefits',
  'faq',
  'lead_form',
  'footer_legal',
];

const PREMIUM_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'media_only',
  'gallery',
  'vehicle_features',
  'final_cta',
  'footer_legal',
];

const FLEET_STARTER: BrandPreset['recommendedBlocks'] = [
  'hero_vehicle_offer',
  'vehicle_features',
  'rich_text',
  'cta_band',
  'lead_form',
  'footer_legal',
];

/**
 * Centralized brand visual presets for premium blocks.
 * Adjust colors and strategies here — do not hardcode in block renderers.
 */
export const BRAND_PRESETS: BrandPreset[] = [
  {
    id: 'opel',
    name: 'Opel',
    category: 'european_mainstream',
    tone: 'light',
    primaryColor: '#f7d300',
    secondaryColor: '#111827',
    accentColor: '#fbbf24',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    fontStrategy: 'geometric-sans',
    buttonStyle: 'pill',
    imageStyle: 'studio-cutout',
    recommendedBlocks: EUROPEAN_STARTER,
  },
  {
    id: 'ford',
    name: 'Ford',
    category: 'american_adventure',
    tone: 'light',
    primaryColor: '#003478',
    secondaryColor: '#0f172a',
    accentColor: '#1d4ed8',
    backgroundColor: '#ffffff',
    textColor: '#0f172a',
    fontStrategy: 'humanist-sans',
    buttonStyle: 'rounded',
    imageStyle: 'lifestyle-bleed',
    recommendedBlocks: AMERICAN_STARTER,
  },
  {
    id: 'dfsk',
    name: 'DFSK',
    category: 'chinese_value_tech',
    tone: 'light',
    primaryColor: '#dc2626',
    secondaryColor: '#1c1917',
    accentColor: '#f59e0b',
    backgroundColor: '#fafaf9',
    textColor: '#1c1917',
    fontStrategy: 'modern-tech-sans',
    buttonStyle: 'rounded',
    imageStyle: 'studio-cutout',
    recommendedBlocks: CHINESE_STARTER,
  },
  {
    id: 'nissan',
    name: 'Nissan',
    category: 'japanese_reliability',
    tone: 'light',
    primaryColor: '#c3002f',
    secondaryColor: '#1f2937',
    accentColor: '#6b7280',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    fontStrategy: 'humanist-sans',
    buttonStyle: 'rounded',
    imageStyle: 'lifestyle-bleed',
    recommendedBlocks: JAPANESE_STARTER,
  },
  {
    id: 'mitsubishi',
    name: 'Mitsubishi',
    category: 'japanese_reliability',
    tone: 'light',
    primaryColor: '#e60012',
    secondaryColor: '#111827',
    accentColor: '#374151',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    fontStrategy: 'humanist-sans',
    buttonStyle: 'rounded',
    imageStyle: 'lifestyle-bleed',
    recommendedBlocks: JAPANESE_STARTER,
  },
  {
    id: 'fiat',
    name: 'Fiat',
    category: 'european_mainstream',
    tone: 'light',
    primaryColor: '#9b0c1c',
    secondaryColor: '#1f2937',
    accentColor: '#64748b',
    backgroundColor: '#ffffff',
    textColor: '#1f2937',
    fontStrategy: 'geometric-sans',
    buttonStyle: 'pill',
    imageStyle: 'studio-cutout',
    recommendedBlocks: EUROPEAN_STARTER,
  },
  {
    id: 'fuso',
    name: 'Fuso',
    category: 'commercial_fleet',
    tone: 'light',
    primaryColor: '#e60012',
    secondaryColor: '#1e293b',
    accentColor: '#475569',
    backgroundColor: '#f1f5f9',
    textColor: '#0f172a',
    fontStrategy: 'industrial-sans',
    buttonStyle: 'rectangular',
    imageStyle: 'utility-side',
    recommendedBlocks: FLEET_STARTER,
  },
  {
    id: 'chery',
    name: 'Chery',
    category: 'chinese_value_tech',
    tone: 'mixed',
    primaryColor: '#ca8a04',
    secondaryColor: '#1c1917',
    accentColor: '#fbbf24',
    backgroundColor: '#fafaf9',
    textColor: '#1c1917',
    fontStrategy: 'modern-tech-sans',
    buttonStyle: 'rounded',
    imageStyle: 'studio-cutout',
    recommendedBlocks: CHINESE_STARTER,
  },
  {
    id: 'foton',
    name: 'Foton',
    category: 'chinese_value_tech',
    tone: 'light',
    primaryColor: '#1d4ed8',
    secondaryColor: '#0f172a',
    accentColor: '#38bdf8',
    backgroundColor: '#ffffff',
    textColor: '#0f172a',
    fontStrategy: 'industrial-sans',
    buttonStyle: 'rectangular',
    imageStyle: 'utility-side',
    recommendedBlocks: FLEET_STARTER,
  },
  {
    id: 'seres',
    name: 'Seres',
    category: 'chinese_value_tech',
    tone: 'dark',
    primaryColor: '#2563eb',
    secondaryColor: '#0b1220',
    accentColor: '#60a5fa',
    backgroundColor: '#0f172a',
    textColor: '#f8fafc',
    fontStrategy: 'modern-tech-sans',
    buttonStyle: 'rounded',
    imageStyle: 'cinematic',
    recommendedBlocks: CHINESE_STARTER,
  },
  {
    id: 'jeep',
    name: 'Jeep',
    category: 'american_adventure',
    tone: 'dark',
    primaryColor: '#1c5429',
    secondaryColor: '#292524',
    accentColor: '#d6d3d1',
    backgroundColor: '#1c1917',
    textColor: '#fafaf9',
    fontStrategy: 'condensed-display',
    buttonStyle: 'rounded',
    imageStyle: 'lifestyle-bleed',
    recommendedBlocks: [
      'hero_vehicle_offer',
      'gallery',
      'vehicle_features',
      'testimonials',
      'lead_form',
      'footer_legal',
    ],
  },
  {
    id: 'gaz',
    name: 'Gaz',
    category: 'commercial_fleet',
    tone: 'light',
    primaryColor: '#1e40af',
    secondaryColor: '#0f172a',
    accentColor: '#64748b',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    fontStrategy: 'industrial-sans',
    buttonStyle: 'rectangular',
    imageStyle: 'utility-side',
    recommendedBlocks: FLEET_STARTER,
  },
  {
    id: 'alfa_romeo',
    name: 'Alfa Romeo',
    category: 'premium_luxury',
    tone: 'dark',
    primaryColor: '#9b0c1c',
    secondaryColor: '#0f172a',
    accentColor: '#94a3b8',
    backgroundColor: '#0f172a',
    textColor: '#f8fafc',
    fontStrategy: 'luxury-serif',
    buttonStyle: 'ghost',
    imageStyle: 'cinematic',
    recommendedBlocks: PREMIUM_STARTER,
  },
  {
    id: 'ford_trucks',
    name: 'Ford Trucks',
    category: 'commercial_fleet',
    tone: 'light',
    primaryColor: '#003478',
    secondaryColor: '#1e293b',
    accentColor: '#2563eb',
    backgroundColor: '#f1f5f9',
    textColor: '#0f172a',
    fontStrategy: 'industrial-sans',
    buttonStyle: 'rectangular',
    imageStyle: 'utility-side',
    recommendedBlocks: FLEET_STARTER,
  },
  {
    id: 'maserati',
    name: 'Maserati',
    category: 'premium_luxury',
    tone: 'dark',
    primaryColor: '#0c2340',
    secondaryColor: '#020617',
    accentColor: '#c0c0c0',
    backgroundColor: '#020617',
    textColor: '#f1f5f9',
    fontStrategy: 'luxury-serif',
    buttonStyle: 'ghost',
    imageStyle: 'cinematic',
    recommendedBlocks: PREMIUM_STARTER,
  },
  {
    id: 'industriel_agricole',
    name: 'Industriel & Agricole',
    category: 'commercial_fleet',
    tone: 'light',
    primaryColor: '#15803d',
    secondaryColor: '#1c1917',
    accentColor: '#ca8a04',
    backgroundColor: '#fafaf9',
    textColor: '#1c1917',
    fontStrategy: 'industrial-sans',
    buttonStyle: 'rectangular',
    imageStyle: 'utility-side',
    recommendedBlocks: FLEET_STARTER,
  },
];

const PRESET_BY_ID = new Map<BrandPresetId, BrandPreset>(
  BRAND_PRESETS.map((preset) => [preset.id, preset]),
);

export function getBrandPreset(id: BrandPresetId): BrandPreset | undefined {
  return PRESET_BY_ID.get(id);
}

export function getAllBrandPresets(): BrandPreset[] {
  return [...BRAND_PRESETS];
}

export function isBrandPresetId(value: string): value is BrandPresetId {
  return PRESET_BY_ID.has(value as BrandPresetId);
}
