export const ALLOWED_BLOCK_TYPES = [
  'promo_autohall',
  'hero_campaign',
  'hero_form_campaign',
  'vehicle_offer',
  'vehicle_features',
  'vehicle_range',
  'gallery',
  'rich_text',
  'media_only',
  'spacer_divider',
  'video_embed',
  'cta_band',
  'pricing_trim',
  'hero',
  'trust_bar',
  'text',
  'image',
  'button',
  'lead_form',
  'benefits',
  'offer_highlights',
  'features',
  'financing',
  'after_sales',
  'testimonials',
  'faq',
  'final_cta',
  'footer_legal',
] as const;

export type AllowedBlockType = (typeof ALLOWED_BLOCK_TYPES)[number];
